services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vlr-api:latest
    container_name: vlr-api
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
    ports:
      - '127.0.0.1:3001:3001'
