name: Build & Deploy

on:
  workflow_dispatch: # Trigger the workflow manually
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: vlr-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "SITE_URL=https://vlr-api.hendraaagil.dev" > .env
          echo "PORT=3001" >> .env

      - name: Set up SSH agent for deployment
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Copy .env file to VPS
        run: |
          scp -o StrictHostKeyChecking=no .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/apps/${{ env.APP_NAME }}/

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Navigate to project directory
            cd ~/apps/${{ env.APP_NAME }}

            # Pull repository
            git pull origin main

            # Stop existing containers
            docker compose down || true

            # Start containers with the locally built image
            docker compose up --build -d
          EOF
