name: Build & Deploy

on:
  workflow_dispatch: # Trigger the workflow manually
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: vlr-api
      CONTAINER_NAME: vlr-api-container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "SITE_URL=https://vlr-api.hendraaagil.dev" > .env
          echo "PORT=3001" >> .env

      - name: Build the Docker image
        run: docker build -t ${{ env.APP_NAME }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker tag ${{ env.APP_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:latest
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:latest

      - name: Set up SSH agent for deployment
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:latest

            # Stop and remove existing container if it's running
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true

            # Run the new container
            docker run -d \
              --restart always \
              --name ${{ env.CONTAINER_NAME }} \
              --memory 256m \
              -p 127.0.0.1:3001:3001
              ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:latest
          EOF
